api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Domain/Stakeholder/Api/Resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
