framework:
    messenger:
        failure_transport: failed

        transports:
            command:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/command'
                retry_strategy:
                    max_retries: 3
            query: 'sync://'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%/failed'

        routing:
            'App\Domain\Stakeholder\Command\Message\RegisterAUser': command
            'App\Domain\Stakeholder\Query\Message\GetAUserByUserId': query
